config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("notices/", include("notices.urls", namespace="notices")),
    path("applications/", include("applications.urls", namespace="applications")),
    path("careers/", include("careers.urls", namespace="careers")),
    path("suggestions/", include("suggestions.urls", namespace="suggestions")),
    path("contracts/", include("contracts.urls", namespace="contracts")),
    path("projects/", include("projects.urls", namespace="projects")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contracts/urls.py
from django.urls import path
from . import views

app_name = "contracts"

urlpatterns = [
    path(
        "<int:employer_pk>/<int:editor_pk>/application/<int:application_pk>/",
        views.create_contract,
        name="create",
    ),
    path("list/", views.ContractListView.as_view(), name="list"),
    path("message/<int:pk>/delete/", views.delete_message, name="delete_message"),
]

core/urls.py
from django.urls import path
from notices import views as notice_views

app_name = "core"

urlpatterns = [
    path("", notice_views.HomeView.as_view(), name="home"),
]

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"
urlpatterns = [
    path("<int:pk>/", views.ProjectView.as_view(), name="list"),
    path(
        "<int:pk>/createproject",
        views.ProjectCreateView.as_view(),
        name="create_project",
    ),
    path(
        "<int:pk>/upload/", views.ProjectFileCreateView.as_view(), name="upload_files"
    ),
    path("<int:pk>/detail/", views.ProjectDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.delete_project, name="delete_project"),
    path(
        "project_file/<int:pk>/delete/",
        views.delete_project_file,
        name="delete_project_file",
    ),
    path(
        "edited_video/<int:pk>/delete/",
        views.delete_edited_video,
        name="delete_edited_video",
    ),
    path("comment/<int:pk>/delete/", views.delete_comment, name="delete_comment"),
    path(
        "edited_video/<int:edited_video_pk>/confirm/",
        views.ConfirmProjectView.as_view(),
        name="confirm_edited_video",
    ),
]

projects/models.py
from django.db import models
from core import models as core_models


class Project(core_models.TimeStampedModel):
    name = models.CharField(max_length=80)
    contract = models.ForeignKey(
        "contracts.Contract", related_name="projects", on_delete=models.CASCADE
    )
    confirmed = models.BooleanField(default=False)


class ProjectFile(core_models.TimeStampedModel):
    project = models.ForeignKey(
        "projects.Project", related_name="files", on_delete=models.CASCADE
    )
    source = models.FileField(upload_to="project_source", null=True, blank=True)

    def get_source_name(self):
        full_name = str(self.source)
        split_name = full_name.split("/")
        return split_name[1]


class EditedVideo(core_models.TimeStampedModel):
    name = models.CharField(max_length=120)
    video = models.FileField(upload_to="edited_video")
    thumbnail = models.ImageField(
        upload_to="edited_video_thumbnail", null=True, blank=True
    )
    project = models.ForeignKey(
        "projects.Project", related_name="edited_videos", on_delete=models.CASCADE
    )
    confirmed = models.BooleanField(default=False)


class Comment(core_models.TimeStampedModel):
    comment = models.TextField()
    user = models.ForeignKey(
        "users.User", related_name="comments", null=True, on_delete=models.CASCADE
    )
    project = models.ForeignKey(
        "projects.Project", related_name="comments", on_delete=models.CASCADE
    )

projects/forms.py
from django import forms
from . import models


class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ("name",)

    def save(self, *args, **kwargs):
        project = super().save(commit=False)
        return project

projects/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.views.generic import ListView, View, DeleteView, FormView
from . import models, forms
from contracts import models as contract_models


class ProjectView(View):
    def get(self, request, pk):
        contract_pk = pk
        contract = contract_models.Contract.objects.get_or_none(pk=contract_pk)
        if contract is None:
            raise Http404
        else:
            queryset = models.Project.objects.filter(contract=contract)
            messages = contract.messages.all()
            return render(
                request,
                "projects/project_list.html",
                {"projects": queryset, "contract": contract, "messages": messages},
            )

    def post(self, *args, **kwargs):
        message = self.request.POST.get("message", None)
        pk = kwargs.get("pk")
        contract = contract_models.Contract.objects.get_or_none(pk=pk)
        if not contract:
            raise Http404()
        if message is not None:
            contract_models.Message.objects.create(
                message=message, user=self.request.user, contract=contract
            )
        return redirect(reverse("projects:list", kwargs={"pk": pk}))


class ProjectCreateView(FormView):
    model = models.Project
    template_name = "projects/project_create.html"
    form_class = forms.CreateProjectForm

    def form_valid(self, form):
        project = form.save()
        contract_pk = self.kwargs.get("pk")
        contract = contract_models.Contract.objects.get_or_none(pk=contract_pk)
        if contract is None:
            raise Http404
        else:
            project.contract = contract
            project.save()
            return redirect(reverse("projects:list", kwargs={"pk": contract_pk}))


class ProjectFileCreateView(View):
    def post(self, *args, **kwargs):
        project_pk = kwargs.get("pk")
        file = self.request.FILES.get("upload_file", None)
        project = models.Project.objects.get_or_none(pk=project_pk)
        if project is None:
            raise Http404
        else:
            contract_pk = project.contract.pk
            if file is not None:
                models.ProjectFile.objects.create(source=file, project=project)
            return redirect(reverse("projects:list", kwargs={"pk": contract_pk}))


class ProjectDetailView(View):
    def get(self, *args, **kwargs):
        project_pk = kwargs.get("pk")
        project = models.Project.objects.get_or_none(pk=project_pk)
        if project is None:
            raise Http404
        else:
            edited_videos = project.edited_videos.all()
            project_comments = project.comments.all()
            return render(
                self.request,
                "projects/project_detail.html",
                {
                    "edited_videos": edited_videos,
                    "project_comments": project_comments,
                    "project": project,
                },
            )

    def post(self, *args, **kwargs):
        message = self.request.POST.get("message", None)
        pk = kwargs.get("pk")
        project = models.Project.objects.get_or_none(pk=pk)
        if not project:
            raise Http404()
        if message is not None:
            models.Comment.objects.create(
                comment=message, user=self.request.user, project=project
            )
        return redirect(reverse("projects:detail", kwargs={"pk": pk}))


class ConfirmProjectView(View):
    def get(self, *args, **kwargs):
        edited_video_pk = kwargs.get("edited_video_pk")
        edited_video = models.EditedVideo.objects.get_or_none(pk=edited_video_pk)
        if edited_video is None:
            return redirect(reverse("core:home"))
        else:
            edited_video.confirmed = True
            edited_video.save()
            project = edited_video.project
            project.confirmed = True
            project.save()
            unconfirmed_videos = project.edited_videos.all()
            for unconfirmed_video in unconfirmed_videos:
                if unconfirmed_video.confirmed is False:
                    unconfirmed_video.delete()
            project.save()
            return redirect(reverse("projects:detail", kwargs={"pk": project.pk}))


@login_required
def delete_edited_video(request, pk):
    user = request.user
    try:
        edited_video = models.EditedVideo.objects.get(pk=pk)
        if edited_video.project.contract.editor == user:
            edited_video.delete()
        next_arg = request.GET.get("next")
        if next_arg is not None:
            return redirect(next_arg)
        else:
            return redirect(reverse("core:home"))
    except models.EditedVideo.DoesNotExist:
        return redirect(reverse("core:home"))


@login_required
def delete_comment(request, pk):
    user = request.user
    try:
        comment = models.Comment.objects.get(pk=pk)
        if comment.user == user:
            comment.delete()
        next_arg = request.GET.get("next")
        if next_arg is not None:
            return redirect(next_arg)
        else:
            return redirect(reverse("core:home"))
    except models.Comment.DoesNotExist:
        return redirect(reverse("core:home"))


@login_required
def delete_project(request, pk):
    user = request.user
    try:
        project = models.Project.objects.get(pk=pk)
        if project.contract.employer == user:
            project.delete()
        next_arg = request.GET.get("next")
        if next_arg is not None:
            return redirect(next_arg)
        else:
            return redirect(reverse("core:home"))
    except models.Project.DoesNotExist:
        return redirect(reverse("core:home"))


def delete_project_file(request, pk):
    user = request.user
    try:
        project_file = models.ProjectFile.objects.get(pk=pk)
        if project_file.project.contract.employer == user:
            project_file.delete()
        next_arg = request.GET.get("next")
        if next_arg is not None:
            return redirect(next_arg)
        else:
            return redirect(reverse("core:home"))
    except models.ProjectFile.DoesNotExist:
        return redirect(reverse("core:home"))

templates/projects/project_create.html
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/projects/project_form.html' with form=form cta="Create Project" %}
    </div>

templates/projects/project_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title> {% block pagename %}{% endblock pagename %} | EF</title>
</head>

<body class="bg-yellow-gray">
    <div>
        {% include "partials/nav2.html" with contract=project.contract %}
        <div class="container w-full xl:w-3/5 mx-auto">
            {% for edited_video in edited_videos %}
                <div class="my-20 border-4 rounded-lg px-5 py-3 relative">
                    <div class="flex justify-between items-center">
                        <div>
                            <span class="m-10 text-4xl">{{edited_video.name}}</span>
                        </div>
                        {% if user == edited_video.project.contract.editor and not edited_video.confirmed%}
                            <div class="flex flex-col">
                                <a href="{% url 'projects:delete_edited_video' edited_video.pk %}?next={{request.path}}" class="border-l-2 border-b-2 border-r-2 hover:bg-red-500 rounded px-2 py-1 mx-auto absolute right-0 top-0 mr-20"><i class="fas fa-trash-alt text-sm mx-1"></i>delete</a>
                                <a href="#" class="absolute right-0 top-0 hover:bg-green-400 rounded px-2 py-1 mx-auto border-l-2 border-b-2"><i class="far fa-edit text-sm mx-1"></i>edit</a>
                            </div>
                        {% endif %}
                    </div>
                    <video oncontextmenu="return false;" class="bg-black w-full h-280px sm:h-360px lg:h-480px xl:h-540px rounded-lg" controls {% if not edited_video.confirmed %} controlsList="nodownload" {% endif %}>
                        <source src="{{edited_video.video.url}}">
                    </video>
                    <span class="text-sm text-gray-600">{{edited_video.created}}</span>
                    {% if user == contract.employer %}
                        <div class="flex">
                            <a href="{% url 'projects:confirm_edited_video' edited_video.pk %}" class="my-5 mx-auto cursor-pointer bg-teal-600 hover:bg-teal-500 shadow-xl px-5 py-2 inline-block text-teal-100 hover:text-white rounded">confirm</a>
                        </div> 
                    {% endif %}
                </div>
            {% endfor %}
            <div class="bg-orange-100 rounded p-5 flex flex-col h-50vh overflow-auto">
                <h1 class="w-auto bg-orange-600 self-start rounded-lg text-white px-3 py-1">댓글</h1>
                <div class="my-5 h-1 w-full bg-white"></div>
                {% for comment in project_comments %}
                    <div class="flex my-1 {% if comment.user.pk == user.pk %} text-right flex-row-reverse {% endif %}">
                        {% if comment.user == user %}       
                            <a href="{% url 'projects:delete_comment' comment.pk %}?next={{request.path}}"><i class="fas fa-trash-alt text-sm mx-1 text-red-600"></i></a>
                        {% endif %}
                        {% include "mixins/user_avatar.html" with user=comment.user lg_h_and_lg_w='lg:w-10 lg:h-10' h_and_w='h-10 w-10' mx='mx-2' md_h_and_md_w='md:w-10 md:h-10' %}
                        <div class="mt-px bg-orange-100 rounded w-4/5 flex-col flex flex-col">
                            <span class="text-lg px-1">{{comment.comment}}</span>
                            <span class="text-xs font-medium text-gray-600">{{comment.created|date:'Y-m-d H:i'}}</span>
                        </div>
                    </div>
                {% endfor %}
                <form class="mt-10 w-full mx-auto flex flex-col" method="POST">
                    {% csrf_token %}
                    <div class="border bg-white rounded pb-2 pl-3">
                    <input class="pb-10 px-10 pt-5 w-full focus:outline-none" name="message" placeholder="Write a Message" required />
                    <button class="mx-auto cursor-pointer bg-red-600 hover:bg-red-500 shadow-xl px-5 py-2 inline-block text-orange-100 hover:text-white rounded">Send Comment</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% include "partials/footer.html" %}
</body>

</html>

templates/projects/project_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title> {% block pagename %}{% endblock pagename %} | EF</title>
</head>

<body class="bg-yellow-gray">
    <div class="h-screen">
        {% include "partials/nav2.html" with contract=contract %}
        <div class="relative container max-w-full flex flex-col-reverse">
            <div id="">
                <span id="jsMessageBtn">뽀잉</span>
            </div>
            <div id="jsMessageContainer" class="hidden lg:absolute lg:right-0 lg:mr-5 lg:top-0 border-4 border-black mt-10 w-full lg:w-2/5 h-screen bg-orange-100 fixed relative flex flex-col p-5 overflow-auto mb-10 rounded-lg shadow hover:shadow-md">
                <h1 class="text-center bg-white px-10 py-2 rounded-full w-full">메세지</h1>
                <div class="my-5"></div>
                {% for comment in messages %}
                    <div class="flex my-1{% if comment.user.pk == user.pk %} text-right flex-row-reverse{% endif %}">
                        {% if comment.user == user %}       
                            <a href="{% url 'contracts:delete_message' comment.pk %}?next={{request.path}}"><i class="fas fa-trash-alt text-xs mx-1 text-red-600"></i></a>
                        {% endif %}
                        {% include "mixins/user_avatar.html" with user=comment.user lg_h_and_lg_w='lg:w-10 lg:h-10' h_and_w='h-10 w-10' mx='mx-2' md_h_and_md_w='md:w-10 md:h-10' %}
                        <div class="mt-px bg-orange-100 rounded w-4/5 flex-col flex flex-col">
                            <span class="text-lg px-1">{{comment.message}}</span>
                            <span class="text-xs font-medium text-gray-600">{{comment.created|date:'Y-m-d H:i'}}</span>
                        </div>
                    </div>
                {% endfor %}
                <form class="w-auto mx-auto flex flex-col relative bottom-0 mb-3 mt-5" method="POST">
                    {% csrf_token %}
                    <div class="border bg-white rounded pb-2 pl-3">
                    <input class="pb-10 px-10 pt-5 w-full focus:outline-none" name="message" placeholder="Write a Message" required />
                    <button class="mx-auto cursor-pointer bg-red-600 hover:bg-red-500 shadow-xl px-5 py-2 inline-block text-orange-100 hover:text-white rounded">Send Comment</button>
                    </div>
                </form>
            </div>
            <div>
                <div class="mt-5 flex flex-row items-center">
                    <div>
                        <span class="ml-10 text-2xl font-bold">
                            {{contract.employer}}
                        </span>
                        <span class="text-2xl">
                            님과 
                        </span>
                        <span class="text-2xl font-bold">
                            {{contract.editor}}
                        </span>
                        <span class="text-2xl">
                            의 프로젝트
                        </span>
                    </div>
                    <div>
                        <a class="px-2 block px-4 py-1 md:p-2 lg:px-4" href="{% url 'projects:create_project' contract.pk %}">
                            <i class="fas fa-plus p-2 bg-black hover:bg-blue-600 text-white rounded-full"></i>
                        </a>
                    </div>
                </div>
                <div class="mx-5 lg:w-3/5 lg:flex lg:flex-wrap">
                    {% for project in projects %}
                        <div class="w-full lg:w-2/5 m-3"> 
                            <div class="hover:shadow-xl rounded-xl h-32 mx-auto p-5 m-5 bg-orange-100 shadow">
                                <div class="text-center">
                                    <a href="{% url 'projects:detail' project.pk %}">
                                        <span class="block text-xl">
                                            {{project.name}}
                                        </span>
                                    </a>
                                </div>
                                <div class="flex flex-row justify-between">
                                    <div>
                                        <span class="block text-xs ml-5 text-gray-600">
                                            {{project.created|date:"m-d - Y"}}
                                        </span>
                                    </div>
                                    <div>
                                        <a class="mx-auto bg-black text-white rounded-lg px-2 py-1 text-xs" href="{% url 'projects:delete_project' project.pk %}?next={{request.path}}">삭제</a>
                                    </div>
                                </div>
                            </div>
                            <div class="mx-5 -mt-20 bg-white h-32 py-3 rounded-xl flex justify-between overflow-auto">
                                <div>
                                    {% if project.files.all %}
                                        {% for file in project.files.all %}
                                            <div class="ml-10">
                                                <span class="text-sm mr-2">⌙ {{file.get_source_name}}</span>
                                                <a href="{{file.source.url}}" download><i class="fas fa-download text-xs"></i></a>
                                                {% if user == project.contract.employer %}
                                                    <a href="{% url 'projects:delete_project_file' file.pk %}?next={{request.path}}"><i class="fas fa-trash-alt text-sm mx-1 text-red-600"></i></a> 
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="flex">
                                    <form method="POST" enctype="multipart/form-data" action="{% url 'projects:upload_files' project.pk %}">
                                        {% csrf_token %}
                                        <label for="ex_file" class="mr-3" style="cursor:pointer;"><i class="fas fa-upload text-blue-700"></i></label>
                                        <input style="display:none;" type="file" id="ex_file" name="upload_file">
                                        <button class="bg-black text-white rounded-lg px-2 py-1 mt-3 text-xs" tpye="submit">추가</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% include "partials/footer.html" %}
    <script src="/static/js/main.js"></script>
</body>

</html>