careers/urls.py
from django.urls import path
from . import views

app_name = "careers"
urlpatterns = [
    path("<int:user_pk>/career/", views.CareerDetailView.as_view(), name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("notices/", include("notices.urls", namespace="notices")),
    path("applications/", include("applications.urls", namespace="applications")),
    path("careers/", include("careers.urls", namespace="careers")),
    path("suggestions/", include("suggestions.urls", namespace="suggestions")),
    path("contracts/", include("contracts.urls", namespace="contracts")),
    path("projects/", include("projects.urls", namespace="projects")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from notices import views as notice_views

app_name = "core"

urlpatterns = [
    path("", notice_views.HomeView.as_view(), name="home"),
]

notices/urls.py
from django.urls import path
from . import views

app_name = "notices"
urlpatterns = [
    path("", views.NoticeListView.as_view(), name="list"),
    path("<int:pk>", views.NoticeDetailView.as_view(), name="detail"),
    path("<int:pk>/delete", views.delete_notice, name="delete"),
    path("create/", views.NoticeCreateView.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("profile", views.UserProfileView.as_view(), name="profile"),
    path("update-profile", views.UpdateProfileView.as_view(), name="update"),
    path("change-password", views.ChangePasswordView.as_view(), name="password"),
]

templates/partials/application_card.html
<div class="{{sm_w|default:'sm:w-1/4'}} {{md_w|default:''}} {{lg_w|default:''}} w-full p-2 overflow-hidden">
    {% if from_profile %}
        {% if application.suggestion %}
            {% if application.suggestion.has_answer %}
                {% if application.suggestion.answer.answer %}
                    <i class="far fa-check-circle text-teal-400 text-2xl"></i>
                {% endif %}
            {% else %}
                <a href="{% url 'suggestions:detail' application.suggestion.pk %}">
                    <i class="fas fa-bell text-3xl text-red-500"></i>
                </a>
            {% endif %}
        {% endif %}
    {% endif %}
    <div class="bg-white px-6 py-8 rounded-lg shadow-md hover:shadow-lg relative flex flex-col">
        {% if application.applicant == user %}
            <a class="absolute right-0 mr-5" href="{% url 'applications:delete' application.pk %}?next={{ request.path }}"><i class="fas fa-trash-alt text-xl"></i></a>
        {% endif %}
        <div class="flex justify-center">
            {% if from_profile %}
                {% include "mixins/user_avatar.html" with user=application.notice.employer lg_h_and_lg_w=lg_h_and_lg_w%}
            {% else %}
                {% include "mixins/user_avatar.html" with user=application.applicant h_and_w='h-32 w-32' md_h_and_md_w='md:h-32 md:w-32' lg_h_and_lg_w='lg:h-32 lg:w-32' %}
            {% endif %}
        </div>
        <span class="text-center text-lg text-gray-800">{{application.applicant.username}}</span>
        <div class="mx-auto">
            <span class="text-xs text-gray-500">편당 가격 :</span>
            <span>{{application.cost}}</span>
            <span class="text-xs text-gray-500">원</span>
        </div>
        <div class="mx-auto">
            <span class="text-xs text-gray-500">나이 :</span>
            <span>{{application.applicant.get_age}}
            <span class="text-xs text-gray-500">세<span>
        </div>
        <div class="flex flex-row justify-around my-5">
            <div>
                <span class="font-light text-sm">계약</span>
            </div>
            <div>
                <span class="font-light text-sm">영상 작업</span>
            </div>
        </div>
        <div class="text-center mt-5 -mb-5 flex justify-around">
            <div>
                {% if notice.employer == user or application.applicant == user %}
                    <a class="text-xs bg-gray-700 hover:bg-gray-600 shadow-xl px-5 py-2 inline-block text-blue-100 hover:text-white rounded" href="{% url 'applications:detail' application.pk %}">자세히</a>
                {% endif %}
            </div>
            {% if not from_profile %}
                <div>
                    <a class="text-xs cursor-pointer bg-orange-600 hover:bg-orange-500 shadow-xl px-5 py-2 inline-block text-orange-100 hover:text-white rounded" href="{% url 'careers:detail' application.applicant.pk %}">경력</a>
                </div>        
            {% endif %}
        </div>
    </div>
</div>

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    &copy; EF
</footer>

templates/partials/nav.html
<ul class="flex items-center tex-sm font-medium h-full w-full py-3 block justify-between md:w-1/2">
    <div>
        <li class="mx-4 sm:hidden">
            <a href="{% url 'core:home' %}">
                EF
            </a>
        </li>
    </div>
    <div class="flex flex-row items-center">
        {% if user.is_authenticated %}
            <li class="mx-4 sm:mx-8 md:mx-2 lg:mx-4">
                <a href="{% url 'notices:create' %}">
                    <span class="cursor-pointer border rounded hover:border-blue-600 px-1 block">
                        편집자 구하기
                        <i class="fas fa-plus"></i>
                    </span>
                </a>
            </li>
            <li class="hover:underline mx-4 sm:mx-8 md:mx-2 lg:mx-4"><a href="{% url 'contracts:list' %}">
                    내 계약
            </a></li>
            <li class="mx-4 sm:mx-8 md:mx-2 lg:mx-4"><a href="{% url 'users:profile'%}">
                {% include "mixins/user_avatar.html" with user=user h_and_w='h-12 w-12' md_h_and_md_w='md:w-12 md:h-12' lg_h_and_lg_w='lg:w-12 lg:h-12'%}
                {% if user.count_unanswered_suggestions_and_answers != 0 %}
                    <span class="text-red-600">({{user.count_unanswered_suggestions_and_answers}})</span>
                {% endif %}
            </a></li>
            <li class="text-sm border border-gray-700 rounded mx-4 sm:mx-8 md:mx-2 lg:mx-4"><a class="" href="{% url 'users:logout' %}">Log out</a></li>
        {% else %}
            <li class="hover:underline mx-4 sm:mx-8 md:mx-2 lg:mx-4"><a href="{% url 'users:login' %}">Login</a></li>
            <li class="hover:underline mx-4 sm:mx-8 md:mx-2 lg:mx-4"><a href="{% url 'users:signup' %}">Sign Up</a></li>
        {% endif %}
    </div>
</ul>

templates/partials/nav2.html
<nav class="bg-white shadow h-auto" role="navigation">
  <div class="container max-w-full p-4 flex flex-wrap items-center md:flex-no-wrap justify-between">
    <div class="ml-4">
        <a href="{% url 'core:home' %}">
            EF
        </a>
    </div>
    <div class="w-full md:w-auto md:flex md:flex md:items-center">
      <ul class="flex flex-col mt-4 -mx-4 pt-4 border-t md:flex-row md:items-center md:mx-0 md:mt-0 md:pt-0 md:mr-4 lg:mr-8 md:border-0">
        <li>
            <a class="hover:text-gray-500 px-2 block px-4 py-1 md:p-2 lg:px-4" href="{% url 'projects:list' contract.pk %}">
                <i class="fas fa-list bg-gray-200 rounded-full p-2"></i>
            </a>
        </li>
        <li>
            <a class="hover:text-gray-500 px-2 block px-4 py-1 md:p-2 lg:px-4" href="#">
                <i class="far fa-envelope p-2 bg-gray-200 rounded-full"></i>
            </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/notice_card.html
<div class="{{sm_w|default:'sm:w-1/2'}} {{md_w|default:'md:w-1/3'}} {{lg_w|default:'lg:w-1/4'}} w-full p-2 overflow-hidden flex flex-col">
    {% if from_profile %}
        {% for application in notice.applications.all %}
            {% if application.suggestion %}
                {% if application.suggestion.has_answer %}
                    {% if application.suggestion.answer.answer %}
                        <a href="{% url 'contracts:create' application.notice.employer.pk application.applicant.pk application.pk %}">
                            <i class="far fa-laugh-beam text-2xl mr-2"></i>
                        </a>
                    {% else %}
                        <a href="{% url 'applications:detail' application.pk %}">
                            <i class="fas fa-frown text-2xl mr-2"></i>
                        </a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'applications:detail' application.pk %}">
                        <i class="fas fa-hourglass-half text-2xl text-yellow-400 mr-2"></i>
                    </a>
                {% endif %}
            {% endif %}
        {% endfor %}
    {%endif%}
    <div class="rounded shadow-md hover:shadow-lg relative bg-white p-5">
        {% if from_profile %}
            <div id="jsNoticeTrash">
                <i class="fas fa-trash-alt text-xl"></i>
                <span id="noticeId" class="hidden">{{notice.id}}</span>
            </div>
        {% endif %}
        <div>
            {% include "mixins/user_avatar.html" with user=notice.employer %}
        </div>
        <span class="block text-center text-lg text-gray-800">{{notice.employer.username}}</span>
        <div class="block text-center mt-1 mb-1 mx-auto text-sm">
            <span ><i class="fab fa-youtube text-red-600 text-lg"></i></span>
            <span>{{notice.employer.youtube_name}}</span>
        </div>
        <li class="block text-center text-xs mx-auto list-none">
            편집주기 : 
            <span class="text-lg">
                {{notice.edited_length}}
            </span>
            일
        </li>
        <li class="block text-center text-xs mx-auto list-none">
            남은 기간 :
            <span class="text-lg">
                {{notice.deadline}}
            </span>
            일
        </li>
        <div class="flex flex-row justify-around my-5">
            <div>
                <span class="font-light text-sm">고용</span>
            </div>
            <div>
                <span class="font-light text-sm">영상 구매</span>
            </div>
        </div>
        <div class="text-center my-3">
            <a class="text-xs bg-gray-700 hover:bg-gray-600 shadow-xl px-5 py-2 inline-block text-blue-100 hover:text-white rounded" href="{% url 'notices:detail' notice.pk %}">자세히</a>
        </div>
        <div class="flex flex-wrap justify-around list-none mt-5 -mb-3">
            {% for g in notice.genre.all %}
                <span class="font-light text-sm text-blue-600">#{{g}}</span>
            {% endfor %}
        </div>
    </div>
</div>