config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("notices/", include("notices.urls", namespace="notices")),
    path("applications/", include("applications.urls", namespace="applications")),
    path("careers/", include("careers.urls", namespace="careers")),
    path("suggestions/", include("suggestions.urls", namespace="suggestions")),
    path("contracts/", include("contracts.urls", namespace="contracts")),
    path("projects/", include("projects.urls", namespace="projects")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from notices import views as notice_views

app_name = "core"

urlpatterns = [
    path("", notice_views.HomeView.as_view(), name="home"),
]

notices/urls.py
from django.urls import path
from . import views

app_name = "notices"
urlpatterns = [
    path("", views.NoticeListView.as_view(), name="list"),
    path("<int:pk>", views.NoticeDetailView.as_view(), name="detail"),
    path("<int:pk>/delete", views.delete_notice, name="delete"),
    path("create/", views.NoticeCreateView.as_view(), name="create"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title> {% block pagename %}{% endblock pagename %} | EF</title>
</head>

<body class="bg-yellow-gray">
    <header class="bg-white container max-w-full items-center flex h-auto shadow-md">
        <div class="flex items-center w-full">
            <div class="hidden sm:block">
            <a class="px-8" href="{% url 'core:home' %}">
                EF
            </a>
            </div>
            <div class="flex flex-col-reverse w-full md:flex-row justify-between items-center">
                <div class="ml-3 md:w-1/2">
                    {% block search-bar %}
                        <form method="GET" action="{% url 'notices:list' %}" class="w-3/4 md:w-1/2 md:mt-2 mb-3 relative text-gray-600">
                            <input class="bg-gray-200 w-full h-10 px-5 pr-10 rounded-full text-sm focus:outline-none" name="youtube_name" placeholder="유튜브 이름으로 검색" />
                            <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                            <svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
                            <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
                            </svg>
                        </button>
                        </form>
                    {% endblock search-bar %}
                    {% block filter %}
                    {% endblock filter %}
                </div>
                <div class="md:hidden mb-5 h-px w-full bg-gray-400"></div>
                {% include "partials/nav.html" %}
            </div>
        </div>            
    </header>
    {% block content %}{% endblock content %}
    {% include "partials/footer.html" %}
    <script src="/static/js/main.js"></script>
</body>

</html>