config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("notices/", include("notices.urls", namespace="notices")),
    path("applications/", include("applications.urls", namespace="applications")),
    path("careers/", include("careers.urls", namespace="careers")),
    path("suggestions/", include("suggestions.urls", namespace="suggestions")),
    path("contracts/", include("contracts.urls", namespace="contracts")),
    path("projects/", include("projects.urls", namespace="projects")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from notices import views as notice_views

app_name = "core"

urlpatterns = [
    path("", notice_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("profile", views.UserProfileView.as_view(), name="profile"),
    path("update-profile", views.UpdateProfileView.as_view(), name="update"),
    path("change-password", views.ChangePasswordView.as_view(), name="password"),
]

users/models.py
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.html import mark_safe
from django.db import models
from core import managers


class User(AbstractUser):
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True)
    youtube_name = models.CharField(max_length=80, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    objects = managers.CustomUserManager()

    def get_thumbnail(self):
        if self.avatar.name != "":
            return mark_safe(f"<img width='100px' src = '{ self.avatar.url }' /img>")
        else:
            return None

    def get_avatar(self):
        return self.avatar.url

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def get_age(self):
        today = date.today()
        k_age = today.year - self.birthdate.year + 1
        return k_age

    def count_unanswered_suggestions_and_answers(self):
        result = 0
        for suggestion in self.received_suggestions.all():
            if suggestion.has_answer is False:
                result = result + 1
        for answer in self.received_answers.all():
            result = result + 1
        return result

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Username"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("username", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["username", "first_name", "last_name", "email"]
        widgets = {
            "username": forms.TextInput(attrs={"placeholder": "Username"}),
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm password"}),
        label="confirm password",
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")
        try:
            models.User.objects.get(username=username)
            raise forms.ValidationError("username already exists")
        except models.User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("User already exists with this email")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("password confirmation doest not match")
        else:
            return password1

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = username
        user.email = email
        user.set_password(password)
        user.save()

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import View, FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    # success_url = reverse_lazy("core:home")
    form_class = forms.LoginForm

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    success_url = reverse_lazy("core:home")
    form_class = forms.SignUpForm

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class UserProfileView(View):
    def get(self, *args, **kwargs):
        user_obj = models.User.objects.get_or_none(pk=self.request.user.pk)
        if user_obj is None:
            raise Http404
        else:
            return render(
                self.request, "users/user_detail.html", {"user_obj": user_obj}
            )


class UpdateProfileView(mixins.LoggedInOnlyView, UpdateView):
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "avatar",
        "youtube_name",
        "birthdate",
    )

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "first_name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "last_name"}
        form.fields["avatar"].widget.attrs = {"placeholder": "avatar"}
        form.fields["youtube_name"].widget.attrs = {"placeholder": "youtube name"}
        form.fields["birthdate"].widget.attrs = {"placeholder": "birthdate"}

        return form


class ChangePasswordView(mixins.LoggedInOnlyView, PasswordChangeView):
    template_name = "users/update-password.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {"placeholder": "old password"}
        form.fields["new_password1"].widget.attrs = {"placeholder": "new password"}
        form.fields["new_password2"].widget.attrs = {
            "placeholder": "new password confirmation"
        }
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()

templates/users/login.html
{% extends "base.html" %}
{% block  pagename %}
    Login
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Login" %}
        <div class="mt-2">
            <span class="mr-2">Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-teal-600 font-medium">Sign up</a>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}
{% block  pagename %}
    Sign Up
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign Up" %}
        <div class="mt-2">
            <span class="mr-2">Have an account?</span>
            <a href="{% url 'users:login' %}" class="text-teal-600 font-medium">Login</a>
        </div>
    </div>
{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}
{% block  pagename %}
    Change Password
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class= "min-h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include 'mixins/auth/auth_form.html' with form=form cta="Change Password" %}
        </div>
    </div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}
{% block  pagename %}
    Update Profile
{% endblock pagename %}
{% block search-bar %}
{% endblock search-bar %}
{% block  content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update" %}
    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}
{% block  pagename %}
    {{user_obj.first_name}}'s profile
{% endblock pagename %}
{% block  content %}
    <div class="flex flex-col xl:flex-row justify-between">
        <div class="bg-white mx-auto list-none container lg:w-5/12 md:w-1/2 xl:w-1/4 mt-32 my-10 flex flex-col items-center p-6 shadow-md">
            {% include "mixins/user_avatar.html" with user=user_obj h_and_w='h-40 w-40' %}
            <div class="my-5 h-px w-full bg-gray-400"></div>
            <div>
                <li class="mb-3">이름: {{user_obj.first_name}}</li>
                <li class="mb-3">성: {{user_obj.last_name}}</li>
                <li class="mb-3">이메일: {{user_obj.email}}</li>
                <li class="mb-3">유튜브 이름: {{user_obj.youtube_name}}</li>
                <li class="mb-3">생일: {{user_obj.birthdate}}</li>
            </div>
            <a class="border text-center" href="{% url 'users:update' %}">Edit Profile</a>
            <a class="border" href="{% url 'users:password' %}">Change Password</a>
        </div>
        <div class="xl:w-1/2 my-10">
            <div class="ml-10">
                <h1 id="jsTest" class="text-3xl font-bold text-gray-700">{{user_obj.first_name}} 님의 공지</h1>
            </div>
            <div class="mt-5 flex flex-wrap">
                {% for notice in user_obj.notices.all %}
                    {% include "partials/notice_card.html" with notice=notice sm_w='sm:w-1/3' lg_w='lg:w-1/3' lg_h_and_lg_w='lg:h-20 lg:w-20' from_profile=True  %}
                {% endfor %}
            </div>
            <div class="my-10 h-px w-full bg-gray-300"></div>
            <div class="ml-10">
                <h1 class="text-3xl font-bold text-gray-700">{{user_obj.first_name}} 님의 지원서</h1>
            </div>
            <div class="mt-5 flex flex-wrap">
                {% for application in user_obj.applications.all %}
                    {% include "partials/application_card.html" with application=application user=user sm_w='sm:w-1/3' lg_h_and_lg_w='lg:h-20 lg:w-20' from_profile=True %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}